### ISSUE TITLE
Victory Column data sequence problem

### ISSUE THREAD

**Issue by Sean0120** [tub-rip/ECRot#1]
Hi 
    Thanks for your great work.
    I just tried to run the code using the Victory Column data sequence and the output is quite strange.
    Seems that there are some problems with this data sequence, it is too small compared with others.

**Comment by Shuang1997** [comment]
Thank you for pointing out my mistake and sorry for my late response.
I uploaded the wrong rosbag files for the "Victory Column", "Square Center" and "Square Side" scenes before, so that their time lengths did not agree to the paper and the github page. I have uploaded the correct files. You are welcome to try the new rosbags out.
